GamingCafe/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('my_profile/<username>', views.MyProfile.as_view(), name='profile'),
    path('buy/confirm_buy/<package_pk>/<curr_user>',views.ConfirmBuyPackage.as_view(), name='confirmbuypackage'),
    path('buy/success/<package_pk>/<curr_user>',views.PackageBuy.as_view(),name='buypackagesuccess'),
]

GamingCafe/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('',views.GameList.as_view(),name='gamelist'),
]

GamingCafe/membership/urls.py
from django.urls import path
from . import views

app_name = 'membership'

urlpatterns = [
    path('', views.MembershipList.as_view(), name='membershiplist'),
]

GamingCafe/package/urls.py
from django.urls import path
from . import views

app_name='package'

urlpatterns = [
    path('',views.PackageList.as_view(),name='packagelist'),
]

GamingCafe/account/models.py
from django.db import models
from membership.models import Membership
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone
from package.models import Package




class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    time_left = models.PositiveIntegerField(default=0)
    total_time = models.PositiveIntegerField(default=0)
    membership_status = models.ForeignKey(
        Membership, on_delete=models.CASCADE, default='The Warrior')
    join_date = models.DateTimeField()

    def __str__(self):
        return str(self.user.username)

    def create_profile(sender, **kwargs):
        user = kwargs["instance"]
        if kwargs["created"]:
            user_profile = UserProfile(user=user, join_date=timezone.now())
            user_profile.save()

    post_save.connect(create_profile, sender=User)


class Receipt(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField()
    mrp = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    amount = models.FloatField()

    def __str__(self):
        return str(self.user)


def package_bought(sender, **kwargs):
        receipt = kwargs["instance"]
        if kwargs['created']:
            userprofile = receipt.user
            package = receipt.package
            userprofile.total_time = userprofile.total_time + package.time_added
            userprofile.time_left = userprofile.time_left + package.time_added
            if(userprofile.total_time > 100 and userprofile.total_time <= 500 and userprofile.membership_status != 'The Mage'):
                membership = Membership.objects.get(rank='The Mage')
                userprofile.membership_status = membership
            elif(userprofile.total_time > 500 and userprofile.total_time <= 5000 and userprofile.membership_status != 'The Knight'):
                membership = Membership.objects.get(rank='The Knight')
                userprofile.membership_status = membership
            elif(userprofile.total_time > 5000 and userprofile.membership_status != 'The Withcer'):
                membership = Membership.objects.get(rank='The Witcher')
                userprofile.membership_status = membership
            userprofile.save()

post_save.connect(package_bought,sender=Receipt)

GamingCafe/game/models.py
from django.db import models

# Create your models here.


class Game(models.Model):
    name = models.CharField(max_length=100, blank=False)
    rating = models.IntegerField()
    description = models.CharField(max_length=500)
    hours_played = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    """def update_hours(sender, **kwargs):
        session = kwargs['instance']
        if kwargs['created']:
            game = session.game
            game.hours_played = game.hours_played + session.duration
            game.save()"""

    #post_save.connect(update_hours, sender=Session)

GamingCafe/membership/models.py
from django.db import models

# Create your models here.


class Membership(models.Model):
    rank = models.CharField(max_length=50, primary_key=True)
    eligibility = models.PositiveIntegerField()
    discount_offered = models.PositiveIntegerField()
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.rank

GamingCafe/package/models.py
from django.db import models

# Create your models here.


class Package(models.Model):
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    time_added = models.PositiveIntegerField()
    description = models.CharField(max_length=256)
    def __str__(self):
        return self.name

GamingCafe/account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import forms
from django.forms.models import ModelForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

GamingCafe/account/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from . import forms
from .models import UserProfile,User,Receipt
from package.models import Package
# Create your views here.


class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('home')
    template_name = 'signup.html'


class MyProfile(generic.DetailView):
    template_name = 'my_profile.html'
    model = UserProfile
    context_object_name = 'userprofile'

    def get_object(self, queryset=None):
        username = self.kwargs['username']
        user = User.objects.get(username=username)
        userprofile = UserProfile.objects.get(user=user)
        return userprofile


class ConfirmBuyPackage(generic.TemplateView):
    template_name='confirmbuypackage.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curr_user = UserProfile.objects.get(user=self.request.user)
        context["curr_user"] = curr_user
        package = Package.objects.get(pk=self.kwargs.get('package_pk'))
        context["package"] = package
        total_discount = package.price * \
            (curr_user.membership_status.discount_offered/100)
        context["total_discount"]=total_discount
        context["total_amount"] = package.price-total_discount
        return context
    

class PackageBuy(generic.TemplateView):
    template_name='buypackage.html'
    def get(self, request, *args, **kwargs):
        user = self.request.user
        userprofile = UserProfile.objects.get(user=user)
        package = Package.objects.get(pk=self.kwargs.get('package_pk'))
        membership = userprofile.membership_status
        discount = membership.discount_offered
        price = package.price
        discount_amt = price*(discount/100)
        total = price - discount_amt
        receipt = Receipt(user=userprofile, package=package, purchase_date=timezone.now(
        ), mrp=package.price, discount=discount, amount=total)
        receipt.save()
        return super().get(request, *args, **kwargs)

GamingCafe/game/views.py
from django.shortcuts import render
from django.views import generic
from .models import Game
# Create your views here.


class GameList(generic.ListView):
    model = Game
    template_name = 'game_list.html'

GamingCafe/membership/views.py
from django.shortcuts import render
from django.views import generic
from .models import Membership
# Create your views here.


class MembershipList(generic.ListView):
    model = Membership
    template_name = 'membership_list.html'

GamingCafe/package/views.py
from django.shortcuts import render
from django.views import generic
from .models import Package
# Create your views here.


class PackageList(generic.ListView):
    model = Package
    template_name='plans.html'

GamingCafe/account/templates/buypackage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/1.jpg' %}">
		<div class="container">
			<h2>Congratulations Package Bought!</h2>
            <a href="{% url 'home' %}" class="site-btn" >Home</a>
			<a href="{% url 'account:profile' username=user %}" class="site-btn" >My Profile</a>
		</div>
	</section>
	<!-- Page top section end -->

{% endblock body_block %}

GamingCafe/account/templates/confirmbuypackage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/1.jpg' %}">
		<div class="container">
			<h2>Final Cart</h2>
		</div>
	</section>
	<!-- Page top section end -->
	{% cycle 'img/game-characters/1.png' 'img/game-characters/2.png' 'img/game-characters/3.png' 'img/game-characters/4.png' as char_image silent %}
    {% if package.pk == 1 %}
    {% elif package.pk == 2 %}
    {% cycle char_image %}
    {% elif package.pk == 3 %}
    {% cycle char_image %}
    {% cycle char_image %}
    {% else %}
    {% cycle char_image %}
    {% cycle char_image %}
    {% cycle char_image %}
    {% endif %}
    <section class="characters-section character-one">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="character-info">
						<img src="{% static 'img/game-characters/title-icon.png' %}" alt="">
						<h2>Cart</h2>
                        <h5>User : {{curr_user}}</h5>
                        <h5>Membership : {{curr_user.membership_status}}</h5>
                        <h5>Package Name : {{package.name}}</h5>
						<h5>Time : {{package.time_added}} Hr.</h5>
						<h5>Price : {{package.price}} Rs.</h5>
                        <h5>Membership Discount : {{curr_user.membership_status.discount_offered}}%</h5>
                        <h5>Total Discount : {{total_discount}}</h5>
                        <h5>Total Amount to Pay : {{total_amount}}</h5>
						<div class="progress-warp">
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-1" data-cpvalue="{{curr_user.time_left}}" data-cpcolor="#10ddb4"></div>
								<h4>Time Left</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-2" data-cpvalue="{{package.time_added}}" data-cpcolor="#10ddb4"></div>
								<h4>Time Added</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-3" data-cpvalue="{{curr_user.time_left|add:package.time_added}}" data-cpcolor="#10ddb4"></div>
								<h4>Total Time</h4>
							</div>
						</div>
						{% if user.is_authenticated %}
						<a href="{% url 'account:buypackagesuccess' package_pk=package.pk curr_user=user %}" class="site-btn">Confirm Buy!</a>
						{% else %}
						<a href="{% url 'account:login' %}" class="site-btn">Login</a>
						<a href="{% url 'account:signup' %}" class="site-btn">Sign Up</a>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="character-img">
				<img src="{% static char_image %}" alt="">
			</div>
		</div>
	</section>

{% endblock body_block %}

GamingCafe/account/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block body_block %}

<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/2.jpg' %}">
		<div class="container">
			<h2>Login!</h2>
		</div>
	</section>
	<!-- Page top section end -->

    <section class="game-section character-one">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
                    <form method='post' class='text-white'>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="Submit" value='Login' class='btn btn-large btn-primary'>
                    </form>
				</div>
			</div>
		</div>
	</section>
{% endblock body_block %}

GamingCafe/account/templates/my_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
    <!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/banner-bg.jpg' %}">
		<div class="container">
			<h2>Welcome @{{userprofile.user}}</h2>
		</div>
	</section>
	<!-- Page top section end -->
    <section class="characters-section character-one">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="character-info">
						<img src="{% static 'img/game-characters/title-icon.png' %}" alt="">
						<h2>{{userprofile.membership_status}}</h2>
						<h5>Join Date : {{userprofile.join_date}}</h5>
						<h5>Email : {{userprofile.user.email}}</h5>
						<p>{{userprofile.membership_status.description}}</p>
						<div class="progress-warp">
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-1" data-cpvalue="{{userprofile.total_time}}" data-cpcolor="#10ddb4"></div>
								<h4>Total Time</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-2" data-cpvalue="{{userprofile.time_left}}" data-cpcolor="#10ddb4"></div>
								<h4>Time Left</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-3" data-cpvalue="{{userprofile.membership_status.discount_offered}}" data-cpcolor="#10ddb4"></div>
								<h4>Discount Offered</h4>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="character-img">
                {% if userprofile.membership_status.rank == "The Warrior" %}
                <img src="{% static 'img/game-characters/2.png' %}" alt="">
                {% elif userprofile.membership_status.rank == "The Mage" %}
                <img src="{% static 'img/game-characters/3.png' %}" alt="">
                {% elif userprofile.membership_status.rank == "The Knight" %}
                <img src="{% static 'img/game-characters/1.png' %}" alt="">
                {% elif userprofile.membership_status.rank == "The Witcher" %}
                <img src="{% static 'img/game-characters/4.png' %}" alt="">
                {% endif %}
				<!--<img src="{% static 'img/game-characters/1.png' %}" alt="">-->
			</div>
		</div>
	</section>
	<!-- Character section 1 end -->



{% endblock body_block %}

GamingCafe/account/templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block body_block %}

<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/2.jpg' %}">
		<div class="container">
			<h2>Register!</h2>
		</div>
	</section>
	<!-- Page top section end -->

    <section class="game-section character-one">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
                    <form action="" method='post' class='text-white'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value='Sign Up' class='btn btn-default'>
            </form>
				</div>
			</div>
		</div>
	</section>
{% endblock body_block %}

GamingCafe/game/templates/game_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/2.jpg' %}">
		<div class="container">
			<h2>Our Games</h2>
		</div>
	</section>
	<!-- Page top section end -->
    {% for game in object_list %}
	{% cycle 'img/game-characters/6.png' 'img/game-characters/7.png' 'img/game-characters/8.png' 'img/game-characters/9.png' as char_image silent %}
    <section class="game-section character-one">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="about-game">
						<div class="game-title mb-0">
							<img src="{% static 'img/game-characters/title-icon.png' %}" alt="">
							<h2>{{game.name}}</h2>
						</div>
						<div class="rating">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<p>{{game.description}}</p>
					</div>
				</div>
				<div class="col-lg-5">
					<div class="about-game-img">
						<img src="{% static char_image %}" alt="">
					</div>
				</div>
			</div>
		</div>
	</section>
    {% endfor %}
{% endblock body_block %}

GamingCafe/membership/templates/membership_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/2.jpg' %}">
		<div class="container">
			<h2>Membership Ranks and Perks</h2>
		</div>
	</section>
	<!-- Page top section end -->
    
	<!-- Characters boxes section -->
	<section class="characters-boxes-section">
		<div class="container">
			<div class="game-title">
				<img src="{% static 'img/game-characters/title-icon.png' %}" alt="">
				<h2>Ranks</h2>
			</div>
            <div class="row">
            {% for membership in object_list %}
            {% cycle 'img/characters-boxes/2.jpg' 'img/characters-boxes/3.jpg' 'img/characters-boxes/1.jpg' 'img/characters-boxes/4.jpg' as membership_image silent %}
                <div class="col-lg-3 col-sm-6">
					<div class="characters-box">
						<img src="{% static membership_image %}" alt="">
						<h4>{{membership.rank}}</h4>
						<p>{{membership.description}}</p>
                        <h5 class='text-white'>Eligibility : {{membership.eligibility}} Hours</h5>
                        <h5 class='text-white'>Discount Offered : {{membership.discount_offered}}%</h5>
					</div>
				</div>
            {% endfor %}
            </div>
	</section>
	<!-- Characters boxes section end -->
{% endblock body_block %}

GamingCafe/package/templates/plans.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/header-bg/1.jpg' %}">
		<div class="container">
			<h2>Plans</h2>
		</div>
	</section>
	<!-- Page top section end -->

	{% for package in object_list %}
	{% cycle 'characters-section character-one' 'characters-section character-two' 'characters-section character-three' 'characters-section character-four' as section_class silent %}
	{% cycle "col-lg-7" "col-lg-7 offset-lg-5" as div_class silent %}
	{% cycle 'img/game-characters/1.png' 'img/game-characters/2.png' 'img/game-characters/3.png' 'img/game-characters/4.png' as char_image silent %}

	<section class="{{section_class}}">
		<div class="container">
			<div class="row">
				<div class="{{div_class}}">
					<div class="character-info">
						<img src="{% static 'img/game-characters/title-icon.png' %}" alt="">
						<h2>{{package.name}}</h2>
						<h5>Time : {{package.time_added}} Hr.</h5>
						<h5>Price : {{package.price}} Rs.</h5>
						<p>{{package.description}}</p>
						<div class="progress-warp">
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-1" data-cpvalue="75" data-cpcolor="#10ddb4"></div>
								<h4>Monthly</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-2" data-cpvalue="90" data-cpcolor="#10ddb4"></div>
								<h4>Quaterly</h4>
							</div>
							<div class="cp-item">
								<div class="circle-progress" data-cpid="id-3" data-cpvalue="80" data-cpcolor="#10ddb4"></div>
								<h4>Yearly</h4>
							</div>
						</div>
						{% if user.is_authenticated %}
						<li><a href="{% url 'account:confirmbuypackage' package_pk=package.pk curr_user=user %}" class="site-btn">Buy</a></li>
						{% else %}
						<a href="{% url 'account:login' %}" class="site-btn">Login</a>
						<a href="{% url 'account:signup' %}" class="site-btn">Sign Up</a>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="character-img">
				<img src="{% static char_image %}" alt="">
			</div>
		</div>
	</section>

	{% endfor %}
	
{% endblock body_block %}

GamingCafe/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zxx">
<head>
	<title>GameQuest - The Gaming Portal</title>
	<meta charset="UTF-8">
	<meta name="description" content="GameQuest - The Gaming Portal">
	<meta name="keywords" content="gaming, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<a href="{% url 'home' %}" class="site-logo">
			<img src="{% static 'img/logo.png' %}" alt="logo">
		</a>
		<ul class="main-menu">
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'game:gamelist' %}">Games</a></li>
			<li><a href="{% url 'package:packagelist' %}">Plans</a></li>
			<li><a href="{% url 'membership:membershiplist' %}">Membership</a></li>
			{% if user.is_authenticated %}
				<li><a href="{% url 'account:profile' username=user %}">My Profile</a></li>
				<li><a href="{% url 'account:logout' %}">Logout</a></li>
			{% else %}
			<li><a href="{% url 'account:login' %}">Login</a></li>
			{% endif %}
		</ul>
		{% if not user.is_authenticated %}
		<ul class="main-menu">
			<form action="{% url 'account:signup' %}">
				<li><input class="login-btn" type="Submit" value="Sign up" href="{% url 'account:signup' %}"></li>
			</form>
		</ul>
		{% endif %}
	</header>
	<!-- Header section end -->

	{% block body_block %}
	{% endblock body_block %}

	<!-- Footer section -->
	<div class="footer-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="footer-widget">
						<div class="about-widget">
							<img src="{% static 'img/logo.png' %}" alt="">
							<p>GameQuest was created with the mission of easing the LAN Gaming transactions with seamless buying transactions and maintaining records.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
						<h2 class="fw-title">Services</h2>
						<ul>
							<li><a href="{% url 'game:gamelist' %}">Games</a></li>
							<li><a href="{% url 'package:packagelist' %}">Plans</a></li>
							<li><a href="{% url 'membership:membershiplist' %}">Memberships</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
						<h2 class="fw-title">Our Team</h2>
						<ul>
							<li><a href="">Dhruvin(B057)</a></li>
							<li><a href="">Maharshi(B055)</a></li>
							<li><a href="">Kshitij(B058)</a></li>
							<li><a href="">Pranay(B059)</a></li>
						</ul>
					</div>
				</div>
			</div>
		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="#"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="#"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href="#"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="#"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="#"><i class="fa fa-youtube"></i><span>youtube</span></a>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer section end -->
															
	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/circle-progress.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>